FROM python:3.10-slim

WORKDIR /app

# Copy HTML files and media
COPY src/html/ .
COPY media/ ./media/

# Copy web server
COPY src/web-server.py .

# Expose port
EXPOSE 8000

# Run custom web server
CMD ["python3", "web-server.py"]
